name: ntlm
description: Library for making HTTP requests that require NTLM authentication
version: 2.0.0
homepage: https://github.com/mrbbot/ntlm

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.1
  pointycastle: ^3.0.0-nullsafety.2
  fixnum: ^1.0.0

dev_dependencies:
  test: ^1.16.8
  pedantic: ^1.11.0
